#!/usr/bin/env bash
set -e
[ -n "$ST2_DEBUG" ] && set -x

version=0.3.0

cd "$ST2_ROOT"
git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
git_revision="${git_revision#v}"

echo "st2 ${git_revision:-$version}"
