#!/usr/bin/env bash
set -e
[ -n "$ST2_DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${ST2_ROOT}" ]; then
  ST2_ROOT="${HOME}/.st2"
else
  ST2_ROOT="${ST2_ROOT%/}"
fi
export ST2_ROOT

if [ -z "${ST2_DIR}" ]; then
  ST2_DIR="$(pwd)"
else
  cd "$ST2_DIR" 2>/dev/null || {
    echo "st2: cannot change working directory to \`$ST2_DIR'"
    exit 1
  } >&2
  ST2_DIR="$(pwd)"
  cd "$OLDPWD"
fi
export ST2_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${ST2_ROOT}/plugins/"*/bin; do
  bin_path="${bin_path}:${plugin_bin}"
done
export PATH="${bin_path}:${PATH}"


command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(st2-version)\n$(st2-help)" >&2
  ;;
"-v" )
  exec st2-version
  ;;
* )
  command_path="$(command -v "st2-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "st2: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
