#!/usr/bin/env bash

set -e

create_project() {
    local project_name="$1"
    local project_directory="$ST2_ROOT/projects"
    local target_dir="$2"

    mkdir -p "$project_directory"

    local project="$project_directory"/"$project_name".sublime-project
    local workspace="$project_directory"/"$project_name".sublime-workspace

    if [ -z "$target_dir" ]; then
      echo "You must provide at least one directory for your project."
      exit 2
    elif [ -f "$project" ]; then
      echo "The project $project_name already exists. Use st2-open "$project_name" to open it."
      exit 2
    else
      touch "$project"
      touch "$workspace"

      echo "{\"folders\":[{\"path\": \""$target_dir"\"}]}" >> "$project"
      echo "{}" >> "$workspace"

      subl -n "$target_dir" --project $project
    fi
}

create_project "$@"
