#!/usr/bin/env bash

set -e

create_project() {
    local project_name="$1"
    local sublime_projects="$ST2_ROOT/projects"
    local target_dir="$2"

    local name=
    local project="$name".sublime-project
    local workspace="$name".sublime-workspace

    if [ -z "$target_dir" ]; then
      echo "Could not find target directory "$target_dir""
    elif [ -ne "$project"]; then
      echo ""$project" already exists as a project"
    else
      touch "$project"
      touch "$workspace"

      echo "{\"folders\":[{\"path\": \""$target_dir"\"}]}" >> "$project"
      echo "{}" >> "$project"

      subl -n -a "$target_dir" --project $project
    fi
}

create_project "$@"
