#!/usr/bin/env bash

set -e

open_file() {
    local project_dir="$ST2_ROOT/projects"
    local project="$project_dir/$1.sublime-project"
    local file="$1"

    shift

    if [ -e "$project" ]; then
        subl --project $project
    elif [ -e "$file" ]; then
        subl "$file" "$@"
    else
        echo "Cannot find $file."
        exit 2
    fi
}

# Provide st2 completions
if [ "$1" = "--complete" ]; then
    exec st2-projects
else
    open_file "$@"
fi
