#!/usr/bin/env bash
set -e
[ -n "$ST2_DEBUG" ] && set -x

case "$1" in
"") echo "usage: st2 <command> [<args>]

Some useful st2 commands are:
   commands      List all st2 commands
   version       Show the current st2 version

See 'st2 help <command>' for information on a specific command.
For full documentation, see: https://github.com/jpfuentes2/st2#readme"
;;
commands) echo "usage: st2 commands

List all st2 commands."
;;
version) echo "usage: st2 version <version>

Displays the current st2 version."
;;
*)
  command_path="$(command -v "st2-$1" || true)"
  if [ -n "$command_path" ]; then
    echo "Sorry, the \`$1' command isn't documented yet."
    echo
    echo "You can view the command's source here:"
    echo "$command_path"
    echo
  else
    echo "st2: no such command \`$1'"
  fi
esac
