#!/usr/bin/env bash
set -e
[ -n "$ST2_DEBUG" ] && set -x

print=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
		shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load st2 automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo 'eval "$(st2 init -)"'
    echo
  } >&2

  exit 1
fi

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/st2.${shell}\""
  ;;
esac

commands=(`st2-commands --sh`)
IFS="|"
cat <<EOS
st2() {
  typeset command
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`st2 "sh-\$command" "\$@"\`;;
  *)
    command st2 "\$command" "\$@";;
  esac
}
EOS
