#!/usr/bin/env bash
set -e
[ -n "$ST2_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: st2 completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "st2-$COMMAND" || command -v "st2-sh-$COMMAND")"
if grep -i "^# provide st2 completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
